### PR TITLE
Did some minor changes to your driver

### PR DESCRIPTION
**Pull request by Tasm-Devil**
Maybe you want to take some changes or maybe this repo is already depreciated :older_man:

### CODE REVIEW

**Comment by Tasm-Devil** [comment]
This question is independent from this pull request: Are there ambitions to merge your pcf8574 interface to this driver: https://github.com/adafruit/Adafruit_CircuitPython_CharLCD in the near future?

**Comment by dhalbert** [comment]
Hi - I'm pleased someone else is using this.

The point of the the separate interface class is that other interfaces exist which I might want to support later. In particular, Adafruit uses the MCP23008 instead of the PCF8574. So I wouldn't want this separation to be factored out. That's the reason I would decline to take this PR.

I wrote this almost two years ago,  before https://github.com/adafruit/Adafruit_CircuitPython_CharLCD existed. I also needed a very minimal version to fit on an M0 board: you can see a stripped-down version in the https://github.com/dhalbert/CircuitPython_LCD/tree/minimal branch. I've since switched to an M4 board for this particular project, so the code size is not as critical. Going forward, I might fork the Adafruit version instead to support the PCF8574. We (Adafruit) doesn't sell a PCF8574 backpack, so we probably wouldn't do this ourselves. In my case, I started on a one-off project (https://github.com/dhalbert/ShortcutBox) using some non-Adafruit display parts before I started working for Adafruit.

So feel free to use your fork of this codebase or support PCF8574 in a fork of the official Adafruit library.

**Comment by dhalbert** [comment]
See https://github.com/adafruit/Adafruit_CircuitPython_CharLCD/issues/29, which talks about adding PCF8574 support to the Adafruit library.

**Comment by Tasm-Devil** [comment]
I expected that you would reject this PR. I will watch if @Tim-Jackins implements the PCF8574 support :-D Thank you for this detailed feedback.

**Comment by Tim-Jackins** [comment]
I have something working! Here's my [fork](https://github.com/Tim-Jackins/Adafruit_CircuitPython_CharLCD?organization=Tim-Jackins&organization=Tim-Jackins). I have more testing to do but feel free to check it out.

**Pull request closed without merging**
